[tool.ruff]
# 启用所有规则
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = []

# 行长度限制
line-length = 100

# 目标 Python 版本
target-version = "py38"

# 排除特定目录
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
]

# 每个文件的规则配置
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101"]

# 导入排序配置
[tool.ruff.isort]
known-first-party = ["robot_control"]
known-third-party = ["numpy", "pandas", "torch", "cv2"]

# 格式化配置
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# mypy 配置
[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

# black 配置
[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'

# isort 配置
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
